waypoints:
  - name: wp1
    frame_id: "map"
    pose:
      position: {x: 0.0, y: 0.0}
      orientation: {z: 0.0, w: 1.0}

  - name: wp2
    frame_id: "map"
    pose:
      position: {x: 2.0, y: 0.5}
      orientation: {z: 0.0, w: 1.0}

  - name: wp3
    frame_id: "map"
    pose:
      position: {x: 2.0, y: -1.0}
      orientation: {z: 0.0, w: 1.0}

  - name: wp4
    frame_id: "map"
    pose:
      position: {x: 0.0, y: -1.5}
      orientation: {z: 0.0, w: 1.0}
