TebLocalPlannerROS:
  max_vel_x: 1.5
  max_vel_x_backwards: 0.0
  max_vel_theta: 4.0
  acc_lim_x: 2.0
  acc_lim_theta: 3.0
  min_turning_radius: 0.10
  wheelbase: 0.25

  weight_optimaltime: 100.0
  weight_kinematics_forward_drive: 50.0
  weight_acc_limit: 1.0
